### ISSUE TITLE
Add templates

### ISSUE THREAD

**Issue by roseline124** [roseline124/wannabe_gatsby#7]
## Todos
- [x] Add page layout: header, footer
- [x] Add body layout: list
- [ ] Design main page
- [ ] Add pagination
- [ ] Add post layout: detail
